default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: user
  password: password
  database: db

development:
  <<: *default
  database: db

test:
  <<: *default
  database: db